package calculator.parser;

import calculator.Programmer;
import calculator.Programmer.ProgrammerException;
import calculator.ProgrammerOperation;
import calculator.parser.antlr.LabeledProgrammerBaseVisitor;
import calculator.parser.antlr.LabeledProgrammerParser;

/**
 * A class that maps the generated parser to the calculator custom classes.
 * This class was not generated by ANTLR, and needs to be manually modified when
 * the grammar changes.
 */
public class ProgrammerParser extends LabeledProgrammerBaseVisitor<Programmer> {

    /*
     * _________________________________ NUMBER _________________________________
     */

    @Override
    public Programmer visitNumberDefault(LabeledProgrammerParser.NumberDefaultContext ctx) {
        try {
            return new Programmer(ctx.getChild(0).getText(), Integer.parseInt(ctx.getChild(2).getText()));
        } catch (ProgrammerException e) {
            return new Programmer(e.getMessage());
        }
    }

    @Override
    public Programmer visitNumberBool(LabeledProgrammerParser.NumberBoolContext ctx) {
        try {
            if (ctx.getChild(0).getText().equals("T") || ctx.getChild(0).getText().equals("t")) {
                return new Programmer("1".toString(), 10);
            }
            return new Programmer("0".toString(), 10);
        } catch (ProgrammerException e) {
            return new Programmer(e.getMessage());
        }
    }

    @Override
    public Programmer visitNumberBinary(LabeledProgrammerParser.NumberBinaryContext ctx) {
        try {
            return new Programmer(ctx.getChild(0).getText().substring(2), 2);
        } catch (ProgrammerException e) {
            return new Programmer(e.getMessage());
        }
    }

    @Override
    public Programmer visitNumberOctal(LabeledProgrammerParser.NumberOctalContext ctx) {
        try {
            return new Programmer(ctx.getChild(0).getText().substring(2), 8);
        } catch (ProgrammerException e) {
            return new Programmer(e.getMessage());
        }
    }

    @Override
    public Programmer visitNumberDecimal(LabeledProgrammerParser.NumberDecimalContext ctx) {
        try {
            return new Programmer(ctx.getChild(0).getText(), 10);
        } catch (ProgrammerException e) {
            return new Programmer(e.getMessage());
        }
    }

    @Override
    public Programmer visitNumberHexa(LabeledProgrammerParser.NumberHexaContext ctx) {
        try {
            return new Programmer(ctx.getChild(0).getText().substring(2), 16);
        } catch (ProgrammerException e) {
            return new Programmer(e.getMessage());
        }
    }

    /*
     * _________________________________ OPERATION _________________________________
     */

    @Override
    public Programmer visitOperationConv(LabeledProgrammerParser.OperationConvContext ctx) {
        try {
            return visit(ctx.getChild(2)).newBase(Integer.parseInt(ctx.getChild(4).getText()));
        } catch (ProgrammerException e) {
            return new Programmer(e.getMessage());
        }
    }

    @Override
    public Programmer visitOperationLshift(LabeledProgrammerParser.OperationLshiftContext ctx) {
        try {
            return ProgrammerOperation.shiftLeft(visit(ctx.getChild(0)), Integer.parseInt(ctx.getChild(2).getText()));
        } catch (ProgrammerException e) {
            return new Programmer(e.getMessage());
        }
    }

    @Override
    public Programmer visitOperationRshift(LabeledProgrammerParser.OperationRshiftContext ctx) {
        try {
            return ProgrammerOperation.shiftRight(visit(ctx.getChild(0)), Integer.parseInt(ctx.getChild(2).getText()));
        } catch (ProgrammerException e) {
            return new Programmer(e.getMessage());
        }
    }

    @Override
    public Programmer visitOperationPrio(LabeledProgrammerParser.OperationPrioContext ctx) {
        return visit(ctx.getChild(1));
    }

    @Override
    public Programmer visitOperationNot(LabeledProgrammerParser.OperationNotContext ctx) {
        try {
            return ProgrammerOperation.not(visit(ctx.getChild(1)));
        } catch (ProgrammerException e) {
            return new Programmer(e.getMessage());
        }
    }

    @Override
    public Programmer visitOperationAnd(LabeledProgrammerParser.OperationAndContext ctx) {
        try {
            return ProgrammerOperation.and(visit(ctx.getChild(0)), visit(ctx.getChild(2)));
        } catch (ProgrammerException e) {
            return new Programmer(e.getMessage());
        }
    }

    @Override
    public Programmer visitOperationOr(LabeledProgrammerParser.OperationOrContext ctx) {
        try {
            return ProgrammerOperation.or(visit(ctx.getChild(0)), visit(ctx.getChild(2)));
        } catch (ProgrammerException e) {
            return new Programmer(e.getMessage());
        }
    }

    @Override
    public Programmer visitOperationXor(LabeledProgrammerParser.OperationXorContext ctx) {
        try {
            return ProgrammerOperation.xor(visit(ctx.getChild(0)), visit(ctx.getChild(2)));
        } catch (ProgrammerException e) {
            return new Programmer(e.getMessage());
        }
    }

    @Override
    public Programmer visitOperationNand(LabeledProgrammerParser.OperationNandContext ctx) {
        try {
            return ProgrammerOperation.nand(visit(ctx.getChild(0)), visit(ctx.getChild(2)));
        } catch (ProgrammerException e) {
            return new Programmer(e.getMessage());
        }
    }

    @Override
    public Programmer visitOperationNor(LabeledProgrammerParser.OperationNorContext ctx) {
        try {
            return ProgrammerOperation.nor(visit(ctx.getChild(0)), visit(ctx.getChild(2)));
        } catch (ProgrammerException e) {
            return new Programmer(e.getMessage());
        }
    }

    @Override
    public Programmer visitOperationImpl(LabeledProgrammerParser.OperationImplContext ctx) {
        try {
            return ProgrammerOperation.implication(visit(ctx.getChild(0)), visit(ctx.getChild(2)));
        } catch (ProgrammerException e) {
            return new Programmer(e.getMessage());
        }
    }

    @Override
    public Programmer visitOperationEquiv(LabeledProgrammerParser.OperationEquivContext ctx) {
        try {
            return ProgrammerOperation.equivalence(visit(ctx.getChild(0)), visit(ctx.getChild(2)));
        } catch (ProgrammerException e) {
            return new Programmer(e.getMessage());
        }
    }
}
