package calculator.parser;

import calculator.parser.antlr.*;

import calculator.Programmer;

/**
 * A class that maps the generated parser to the calculator custom classes.
 * This class was not generated by ANTLR, and needs to be manually modified when
 * the grammar changes.
 */
public class ProgrammerParser extends LabeledProgrammerBaseVisitor<Programmer> {
    @Override
    public Programmer visitNumberDefault(LabeledProgrammerParser.NumberDefaultContext ctx) {
        return new Programmer(ctx.getChild(0).getText(), Integer.parseInt(ctx.getChild(2).getText()));
    }
}
